language: go

before_install:
 - chmod +x setup_dependencies.sh
 - ./setup_dependencies.sh

install:
 - chmod +x install-dependencies.sh
 - ./install-dependencies.sh

script:
 - cd $CURRENT_BUILD_PATH
 - go build
